repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.1
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Sort imports
    - id: ruff
      name: sort imports with ruff
      args: [--select, I, --fix]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]